export const SUPABASE_URL="https://wvadgyzlqigfnjakdmrb.supabase.co"
export const SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2YWRneXpscWlnZm5qYWtkbXJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTEwOTYxMDgsImV4cCI6MjAwNjY3MjEwOH0.hP5jnoyr3eFdvsmP1ERVNdrwc-E6JFiNJs8EVO2TiE4"


